Repository SC-ECE/CONTENT, pull requests merged in 2023-01, with the labels that each got.

#6 Social Media dating apps crime
  Social Media Dating Apps Crime/README.md
  Social Media Dating Apps Crime/Social media dating apps.docx
Labels: Synapse, Medium

#7 2nd Repo- The Indian Startups- a way to atmanirbhar renaissance
  The Indian Startups- a way to atmanirbhar renaissance/README.md
  The Indian Startups- a way to atmanirbhar renaissance/The Indian Startups- a way to atmanirbhar renaissance.docx
Labels: Synapse

#8 3rd Repo- Bengali Culture
  Bengali Culture/README.md
  Bengali Culture/Repo3-Bengali culture.docx
Labels: Synapse, Easy

#9 Repo 4- Are EdTech startups looting india of their dream?
  Are EdTech startups looting india of their dream/README.md
  Are EdTech startups looting india of their dream/Repo4-Are EdTech startups looting india of their dream.docx
Labels: Synapse, Medium

#10 Repo 5- Virtual Reality Gaming
  Virtual Reality Gaming/README.md
  Virtual Reality Gaming/Repo5- Virtual Reality Gaming.docx
Labels: Synapse, Easy

#12 6th repo- Engineering helps you grow your character
  Engineering is helpful to grow your character/Engineering character.docx
  Engineering is helpful to grow your character/README.md
Labels: Synapse, Easy

#13 7th repo- Engineering Hostel life
  Engineering Hostel life/README.md
  Engineering Hostel life/engineering hostel life.docx
Labels: Synapse, Medium

#14 8th Repo- AI threat to humanity
  AI- threat to humanity/AI- threat to humanity.docx
  AI- threat to humanity/README.md
Labels: Medium

#15 crypto
  crypto/Crypto is the currency of failure.docx
  crypto/readme.md
Labels: Medium

#11 Recession plays a key role in unemployment
  SYNAPSE/README.md
  SYNAPSE/hello.txt
Labels: Medium
